### ISSUE TITLE
OSError: [Errno 121] Remote I/O error

### ISSUE THREAD

**Issue by samuk** [ANI717/ANI717_Robotics#2]
When building this https://github.com/ANI717/ANI717_Robotics/tree/main/robot_ws/src/ros2-twist-message-to-robot-motion

I got some permission denied errors on i2c. Those went away with a sudo chmod a+rw /dev/i2c-*

I now get:
/ANI717_Robotics/robot_ws$ colcon build && source install/setup.bash && ros2 run ros2_twist_message_to_robot_motion execute
Starting >>> robot_launch
Starting >>> ros2_gamepad_to_twist_message
Starting >>> ros2_pytorch_model_to_twist_message
Starting >>> ros2_save_camera_image
Finished <<< robot_launch [10.8s]
Starting >>> ros2_twist_message_to_robot_motion
Finished <<< ros2_pytorch_model_to_twist_message [10.8s]
Finished <<< ros2_gamepad_to_twist_message [11.0s]
Starting >>> set_environment
Finished <<< ros2_save_camera_image [11.0s]
Finished <<< set_environment [6.99s]
Finished <<< ros2_twist_message_to_robot_motion [7.66s]

Summary: 6 packages finished [21.8s]
Traceback (most recent call last):
  File "/home/ubuntu/dev_ws/follower/ANI717_Robotics/robot_ws/install/ros2_twist_message_to_robot_motion/lib/ros2_twist_message_to_robot_motion/execute", line 11, in <module>
    load_entry_point('ros2-twist-message-to-robot-motion==0.0.0', 'console_scripts', 'execute')()
  File "/home/ubuntu/dev_ws/follower/ANI717_Robotics/robot_ws/install/ros2_twist_message_to_robot_motion/lib/python3.8/site-packages/ros2_twist_message_to_robot_motion/jetbot_motion.py", line 206, in main
    twist_to_motion = Twist_to_Motion()
  File "/home/ubuntu/dev_ws/follower/ANI717_Robotics/robot_ws/install/ros2_twist_message_to_robot_motion/lib/python3.8/site-packages/ros2_twist_message_to_robot_motion/jetbot_motion.py", line 51, in __init__
    self.robot = Robot()
  File "/home/ubuntu/dev_ws/follower/ANI717_Robotics/robot_ws/install/ros2_twist_message_to_robot_motion/lib/python3.8/site-packages/ros2_twist_message_to_robot_motion/jetbot_motion.py", line 173, in __init__
    self.motor_driver = Adafruit_MotorHAT(i2c_bus=self.i2c_bus)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/Adafruit_MotorHAT/Adafruit_MotorHAT_Motors.py", line 231, in __init__
    self._pwm = PWM(addr, debug=False, i2c=i2c, i2c_bus=i2c_bus)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/Adafruit_MotorHAT/Adafruit_PWM_Servo_Driver.py", line 59, in __init__
    self.setAllPWM(0, 0)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/Adafruit_MotorHAT/Adafruit_PWM_Servo_Driver.py", line 95, in setAllPWM
    self.i2c.write8(self.__ALL_LED_ON_L, on & 0xFF)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/Adafruit_GPIO/I2C.py", line 114, in write8
    self._bus.write_byte_data(self._address, register, value)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/Adafruit_PureIO/smbus.py", line 327, in write_byte_data
    self._device.write(data)
OSError: [Errno 121] Remote I/O error

Are there any useful logs I can give you?

**Comment by samuk** [comment]
Nothing connected!
